### ISSUE TITLE
Example in README has Typo's

### ISSUE THREAD

**Issue by MauriceVeraart** [SuperFlyTV/supertimeline#29]
in the README.MD example some Caps are not there
```
Timeline.resolver.getTimelineInWindow
should be
Timeline.Resolver.getTimelineInWindow

Timeline.enums.TriggerType.
should be
Timeline.Enums.TriggerType.

etc etc
``

kind regards maurice

**Comment by nytamin** [comment]
Thank you!
I've updated the readme, let me know if you find anything else.
The readme has fallen behind a bit, I'm afraid. Especially when it comes to examples.

For inspiration, check out these examples of the timeline in action: [here](https://github.com/nrkno/tv-automation-state-timeline-resolver/tree/master/examples) and [here](https://github.com/nrkno/tv-automation-state-timeline-resolver/tree/master/src/__tests__).

Cheers!
