### ISSUE TITLE
start, end, duration manipulation 

### ISSUE THREAD

**Issue by MauriceVeraart** [SuperFlyTV/supertimeline#58]
* **I'm submitting a ...**
[x] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
I don't know if this is a feature request or a bug report ;)
if I change this (works)
```
{ // This object defines a graphic, to be overlaid on the video
        id: 'graphic0',
        layer: 'L2',
        enable: {
            start: '#video0.start + 10', // 10 after video0 starts
            duration: 10
        },
        content: {},
        classes: ['graphics']
    }
```
into this 

```
{ // This object defines a graphic, to be overlaid on the video
        id: 'graphic0',
        layer: 'L2',
        enable: {
            start: '#video0.duration / 2', // graphic should start halfway 
            duration: 10
        },
        content: {},
        classes: ['graphics']
    }
```
it does not work.
I don't know how far / if this kind of (start / end / duration) manipulation is supported
if not supported this is a feature request ;) other wise a bug report

**Comment by baltedewit** [comment]
I think it will work like this:

```
{ // This object defines a graphic, to be overlaid on the video
        id: 'graphic0',
        layer: 'L2',
        enable: {
            start: '#video0.start + #video0.duration / 2', // graphic should start halfway 
            duration: 10
        },
        content: {},
        classes: ['graphics']
    }
```

And if this is to be used with the TSR library you should probably add the duration in ms.

**Comment by MauriceVeraart** [comment]
Stupid me ;)
I tried to start a graphic somewhere in 1970 ;)
sorry for bothering

**Comment by jesperstarkar** [comment]
Don't you have a public testbench for tsr somewhere @nytamin ?

**Comment by nytamin** [comment]
Sure, there's the Timeline visualizer in a jsfiddle here: https://jsfiddle.net/nytamin/rztp517u/
